### ISSUE TITLE
Improve the app stability 

### ISSUE THREAD

**Issue by SkyleKayma** [openium/auvergne-webcams-droid#11]
Some minor bugs still exist and need to be solved. It will probably take more than one version to solve all of them, but we are working on.

**Comment by SkyleKayma** [comment]
Fixed in bd61ebb90ef22ff1775f5f30946c55305976610d

**Comment by lariviere15** [comment]
Crashs still happen

**Comment by lariviere15** [comment]
Crash on refresh video webcam 8631b8c

**Comment by lariviere15** [comment]
Crash realm access 144b01b
