### ISSUE TITLE
Add webcam

### ISSUE THREAD

**Issue by ctlui** [openium/auvergne-webcams-droid#5]
Hi,
Is it possible to add some webcam from here:
http://public.dir-massif-central.magsys-services.net/
You can find some of them here also:
http://www.inforoute-massif-central.fr/
Thanks

**Comment by Drusy** [comment]
Hi @ctlui,

It sure is, thanks for the links. 
We will include those webcams in the coming weeks.

Best Regards

**Comment by Drusy** [comment]
From http://www.inforoute-massif-central.fr, the webcams are fetch using the following request:

> curl 'http://www.inforoute-massif-central.fr/mod_turbolead/mod/inforoute/webcam.php' -H 'Pragma: no-cache' -H 'Origin: http://www.inforoute-massif-central.fr' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,de;q=0.5,cs;q=0.4,pt;q=0.3,la;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'Referer: http://www.inforoute-massif-central.fr/' -H 'Cookie: PHPSESSID=hd2nfq0ksvm8qqpn7gc5n25qn6' -H 'Connection: keep-alive' --data 'type=dirmc&dossier=%2Fvar%2Fwww%2Finforoute-massif-central.fr%2Fweb%2Fwebcam%2Fcam18%2F&id=15' --compressed

**Comment by Drusy** [comment]
From http://public.dir-massif-central.magsys-services.net/, the webcams are fetch using the following request:

> curl 'http://public.dir-massif-central.magsys-services.net/index.php/camera/ajaxRefresh' -H 'Pragma: no-cache' -H 'Origin: http://public.dir-massif-central.magsys-services.net' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,de;q=0.5,cs;q=0.4,pt;q=0.3,la;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: symfony=3kpvdl94383rhe09l9e09b5612' -H 'Connection: keep-alive' -H 'Referer: http://public.dir-massif-central.magsys-services.net/' --data 'cam_id=3&cam_dir=%2Findex.php%2F&cam_width=undefined&cam_height=undefined&cam_frame=0&cam_previous=stream%2Fcam3%2Fimg_2018-02-12_15-52-34_23.jpg' --compressed

**Comment by Drusy** [comment]
2 PHP proxy have been developed to ease the display of the webcam on the apps. You should see the webcams on the apps this week.

**Comment by Drusy** [comment]
Webcams should now be available
